const children = [
    {
        value:'01班',
        label:'01班'
    },
    {
        value:'02班',
        label:'02班'
    },
    {
        value:'03班',
        label:'03班'
    },
    {
        value:'04班',
        label:'04班'
    },
    {
        value:'05班',
        label:'05班'
    },
    {
        value:'06班',
        label:'06班'
    },
    {
        value:'07班',
        label:'07班'
    },
    {
        value:'08班',
        label:'08班'
    },{
        value:'09班',
        label:'09班'
    }
]
const classes = [
    {
        value:'软件工程',
        label:'软件工程',
        children
    },
    {
        value:'计算机科学与技术',
        label:'计算机科学与技术',
        children
    },
    {
        value:'数字媒体技术',
        label:'数字媒体技术',
        children
    },
    {
        value:'数字经济',
        label:'数字经济',
        children
    },
    {
        value:'轨道交通电气与控制',
        label:'轨道交通电气与控制',
        children
    },
    {
        value:'动画',
        label:'动画',
        children
    },
    {
        value:'广播电视编导',
        label:'广播电视编导',
        children
    },
    {
        value:'车辆工程',
        label:'车辆工程',
        children
    },
    {
        value:'通信工程',
        label:'通信工程',
        children
    }
]

export default classes